window.esdocSearchIndex = [
  [
    "@solana/web3~account",
    "class/src/account.js~Account.html",
    "<span>Account</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~bpfloader",
    "class/src/bpf-loader.js~BpfLoader.html",
    "<span>BpfLoader</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~budgetprogram",
    "class/src/budget-program.js~BudgetProgram.html",
    "<span>BudgetProgram</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~connection",
    "class/src/connection.js~Connection.html",
    "<span>Connection</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~getconfirmedblockrpcresult",
    "variable/index.html#static-variable-GetConfirmedBlockRpcResult",
    "<span>GetConfirmedBlockRpcResult</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~loader",
    "class/src/loader.js~Loader.html",
    "<span>Loader</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~packet_data_size",
    "variable/index.html#static-variable-PACKET_DATA_SIZE",
    "<span>PACKET_DATA_SIZE</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~publickey",
    "class/src/publickey.js~PublicKey.html",
    "<span>PublicKey</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~sol_lamports",
    "variable/index.html#static-variable-SOL_LAMPORTS",
    "<span>SOL_LAMPORTS</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~sysvar_rent_pubkey",
    "variable/index.html#static-variable-SYSVAR_RENT_PUBKEY",
    "<span>SYSVAR_RENT_PUBKEY</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~systeminstruction",
    "class/src/system-program.js~SystemInstruction.html",
    "<span>SystemInstruction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~systemprogram",
    "class/src/system-program.js~SystemProgram.html",
    "<span>SystemProgram</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~transaction",
    "class/src/transaction.js~Transaction.html",
    "<span>Transaction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~transactioninstruction",
    "class/src/transaction.js~TransactionInstruction.html",
    "<span>TransactionInstruction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~validator_info_key",
    "variable/index.html#static-variable-VALIDATOR_INFO_KEY",
    "<span>VALIDATOR_INFO_KEY</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~vote_account_key",
    "variable/index.html#static-variable-VOTE_ACCOUNT_KEY",
    "<span>VOTE_ACCOUNT_KEY</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "variable"
  ],
  [
    "@solana/web3~validatorinfo",
    "class/src/validator-info.js~ValidatorInfo.html",
    "<span>ValidatorInfo</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~voteaccount",
    "class/src/vote-account.js~VoteAccount.html",
    "<span>VoteAccount</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "class"
  ],
  [
    "@solana/web3~decodelength",
    "function/index.html#static-function-decodeLength",
    "<span>decodeLength</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~encodelength",
    "function/index.html#static-function-encodeLength",
    "<span>encodeLength</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~getalloc",
    "function/index.html#static-function-getAlloc",
    "<span>getAlloc</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~publickey",
    "function/index.html#static-function-publicKey",
    "<span>publicKey</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~ruststring",
    "function/index.html#static-function-rustString",
    "<span>rustString</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~sendandconfirmrawtransaction",
    "function/index.html#static-function-sendAndConfirmRawTransaction",
    "<span>sendAndConfirmRawTransaction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~sendandconfirmrecenttransaction",
    "function/index.html#static-function-sendAndConfirmRecentTransaction",
    "<span>sendAndConfirmRecentTransaction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~sendandconfirmtransaction",
    "function/index.html#static-function-sendAndConfirmTransaction",
    "<span>sendAndConfirmTransaction</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~sleep",
    "function/index.html#static-function-sleep",
    "<span>sleep</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~testnetchannelendpoint",
    "function/index.html#static-function-testnetChannelEndpoint",
    "<span>testnetChannelEndpoint</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "@solana/web3~uint64",
    "function/index.html#static-function-uint64",
    "<span>uint64</span> <span class=\"search-result-import-path\">@solana/web3</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/account.js",
    "file/src/account.js.html",
    "src/account.js",
    "file"
  ],
  [
    "src/account.js~account#constructor",
    "class/src/account.js~Account.html#instance-constructor-constructor",
    "src/account.js~Account#constructor",
    "method"
  ],
  [
    "src/account.js~account#publickey",
    "class/src/account.js~Account.html#instance-get-publicKey",
    "src/account.js~Account#publicKey",
    "member"
  ],
  [
    "src/account.js~account#secretkey",
    "class/src/account.js~Account.html#instance-get-secretKey",
    "src/account.js~Account#secretKey",
    "member"
  ],
  [
    "src/blockhash.js",
    "file/src/blockhash.js.html",
    "src/blockhash.js",
    "file"
  ],
  [
    "src/blockhash.js~blockhhash",
    "typedef/index.html#static-typedef-Blockhhash",
    "src/blockhash.js~Blockhhash",
    "typedef"
  ],
  [
    "src/bpf-loader.js",
    "file/src/bpf-loader.js.html",
    "src/bpf-loader.js",
    "file"
  ],
  [
    "src/bpf-loader.js~bpfloader.getminnumsignatures",
    "class/src/bpf-loader.js~BpfLoader.html#static-method-getMinNumSignatures",
    "src/bpf-loader.js~BpfLoader.getMinNumSignatures",
    "method"
  ],
  [
    "src/bpf-loader.js~bpfloader.load",
    "class/src/bpf-loader.js~BpfLoader.html#static-method-load",
    "src/bpf-loader.js~BpfLoader.load",
    "method"
  ],
  [
    "src/bpf-loader.js~bpfloader.programid",
    "class/src/bpf-loader.js~BpfLoader.html#static-get-programId",
    "src/bpf-loader.js~BpfLoader.programId",
    "member"
  ],
  [
    "src/budget-program.js",
    "file/src/budget-program.js.html",
    "src/budget-program.js",
    "file"
  ],
  [
    "src/budget-program.js~budgetcondition",
    "typedef/index.html#static-typedef-BudgetCondition",
    "src/budget-program.js~BudgetCondition",
    "typedef"
  ],
  [
    "src/budget-program.js~budgetprogram.applysignature",
    "class/src/budget-program.js~BudgetProgram.html#static-method-applySignature",
    "src/budget-program.js~BudgetProgram.applySignature",
    "method"
  ],
  [
    "src/budget-program.js~budgetprogram.applytimestamp",
    "class/src/budget-program.js~BudgetProgram.html#static-method-applyTimestamp",
    "src/budget-program.js~BudgetProgram.applyTimestamp",
    "method"
  ],
  [
    "src/budget-program.js~budgetprogram.pay",
    "class/src/budget-program.js~BudgetProgram.html#static-method-pay",
    "src/budget-program.js~BudgetProgram.pay",
    "method"
  ],
  [
    "src/budget-program.js~budgetprogram.payonboth",
    "class/src/budget-program.js~BudgetProgram.html#static-method-payOnBoth",
    "src/budget-program.js~BudgetProgram.payOnBoth",
    "method"
  ],
  [
    "src/budget-program.js~budgetprogram.programid",
    "class/src/budget-program.js~BudgetProgram.html#static-get-programId",
    "src/budget-program.js~BudgetProgram.programId",
    "member"
  ],
  [
    "src/budget-program.js~budgetprogram.signaturecondition",
    "class/src/budget-program.js~BudgetProgram.html#static-method-signatureCondition",
    "src/budget-program.js~BudgetProgram.signatureCondition",
    "method"
  ],
  [
    "src/budget-program.js~budgetprogram.space",
    "class/src/budget-program.js~BudgetProgram.html#static-get-space",
    "src/budget-program.js~BudgetProgram.space",
    "member"
  ],
  [
    "src/budget-program.js~budgetprogram.timestampcondition",
    "class/src/budget-program.js~BudgetProgram.html#static-method-timestampCondition",
    "src/budget-program.js~BudgetProgram.timestampCondition",
    "method"
  ],
  [
    "src/budget-program.js~payment",
    "typedef/index.html#static-typedef-Payment",
    "src/budget-program.js~Payment",
    "typedef"
  ],
  [
    "src/budget-program.js~signaturecondition",
    "typedef/index.html#static-typedef-SignatureCondition",
    "src/budget-program.js~SignatureCondition",
    "typedef"
  ],
  [
    "src/budget-program.js~timestampcondition",
    "typedef/index.html#static-typedef-TimestampCondition",
    "src/budget-program.js~TimestampCondition",
    "typedef"
  ],
  [
    "src/connection.js",
    "file/src/connection.js.html",
    "src/connection.js",
    "file"
  ],
  [
    "src/connection.js~accountinfo",
    "typedef/index.html#static-typedef-AccountInfo",
    "src/connection.js~AccountInfo",
    "typedef"
  ],
  [
    "src/connection.js~commitment",
    "typedef/index.html#static-typedef-Commitment",
    "src/connection.js~Commitment",
    "typedef"
  ],
  [
    "src/connection.js~confirmedblock",
    "typedef/index.html#static-typedef-ConfirmedBlock",
    "src/connection.js~ConfirmedBlock",
    "typedef"
  ],
  [
    "src/connection.js~connection#confirmtransaction",
    "class/src/connection.js~Connection.html#instance-method-confirmTransaction",
    "src/connection.js~Connection#confirmTransaction",
    "method"
  ],
  [
    "src/connection.js~connection#confirmtransactionandcontext",
    "class/src/connection.js~Connection.html#instance-method-confirmTransactionAndContext",
    "src/connection.js~Connection#confirmTransactionAndContext",
    "method"
  ],
  [
    "src/connection.js~connection#constructor",
    "class/src/connection.js~Connection.html#instance-constructor-constructor",
    "src/connection.js~Connection#constructor",
    "method"
  ],
  [
    "src/connection.js~connection#getaccountinfo",
    "class/src/connection.js~Connection.html#instance-method-getAccountInfo",
    "src/connection.js~Connection#getAccountInfo",
    "method"
  ],
  [
    "src/connection.js~connection#getaccountinfoandcontext",
    "class/src/connection.js~Connection.html#instance-method-getAccountInfoAndContext",
    "src/connection.js~Connection#getAccountInfoAndContext",
    "method"
  ],
  [
    "src/connection.js~connection#getbalance",
    "class/src/connection.js~Connection.html#instance-method-getBalance",
    "src/connection.js~Connection#getBalance",
    "method"
  ],
  [
    "src/connection.js~connection#getbalanceandcontext",
    "class/src/connection.js~Connection.html#instance-method-getBalanceAndContext",
    "src/connection.js~Connection#getBalanceAndContext",
    "method"
  ],
  [
    "src/connection.js~connection#getclusternodes",
    "class/src/connection.js~Connection.html#instance-method-getClusterNodes",
    "src/connection.js~Connection#getClusterNodes",
    "method"
  ],
  [
    "src/connection.js~connection#getconfirmedblock",
    "class/src/connection.js~Connection.html#instance-method-getConfirmedBlock",
    "src/connection.js~Connection#getConfirmedBlock",
    "method"
  ],
  [
    "src/connection.js~connection#getepochinfo",
    "class/src/connection.js~Connection.html#instance-method-getEpochInfo",
    "src/connection.js~Connection#getEpochInfo",
    "method"
  ],
  [
    "src/connection.js~connection#getepochschedule",
    "class/src/connection.js~Connection.html#instance-method-getEpochSchedule",
    "src/connection.js~Connection#getEpochSchedule",
    "method"
  ],
  [
    "src/connection.js~connection#getinflation",
    "class/src/connection.js~Connection.html#instance-method-getInflation",
    "src/connection.js~Connection#getInflation",
    "method"
  ],
  [
    "src/connection.js~connection#getminimumbalanceforrentexemption",
    "class/src/connection.js~Connection.html#instance-method-getMinimumBalanceForRentExemption",
    "src/connection.js~Connection#getMinimumBalanceForRentExemption",
    "method"
  ],
  [
    "src/connection.js~connection#getprogramaccounts",
    "class/src/connection.js~Connection.html#instance-method-getProgramAccounts",
    "src/connection.js~Connection#getProgramAccounts",
    "method"
  ],
  [
    "src/connection.js~connection#getrecentblockhash",
    "class/src/connection.js~Connection.html#instance-method-getRecentBlockhash",
    "src/connection.js~Connection#getRecentBlockhash",
    "method"
  ],
  [
    "src/connection.js~connection#getrecentblockhashandcontext",
    "class/src/connection.js~Connection.html#instance-method-getRecentBlockhashAndContext",
    "src/connection.js~Connection#getRecentBlockhashAndContext",
    "method"
  ],
  [
    "src/connection.js~connection#getsignaturestatus",
    "class/src/connection.js~Connection.html#instance-method-getSignatureStatus",
    "src/connection.js~Connection#getSignatureStatus",
    "method"
  ],
  [
    "src/connection.js~connection#getslot",
    "class/src/connection.js~Connection.html#instance-method-getSlot",
    "src/connection.js~Connection#getSlot",
    "method"
  ],
  [
    "src/connection.js~connection#getslotleader",
    "class/src/connection.js~Connection.html#instance-method-getSlotLeader",
    "src/connection.js~Connection#getSlotLeader",
    "method"
  ],
  [
    "src/connection.js~connection#gettotalsupply",
    "class/src/connection.js~Connection.html#instance-method-getTotalSupply",
    "src/connection.js~Connection#getTotalSupply",
    "method"
  ],
  [
    "src/connection.js~connection#gettransactioncount",
    "class/src/connection.js~Connection.html#instance-method-getTransactionCount",
    "src/connection.js~Connection#getTransactionCount",
    "method"
  ],
  [
    "src/connection.js~connection#getversion",
    "class/src/connection.js~Connection.html#instance-method-getVersion",
    "src/connection.js~Connection#getVersion",
    "method"
  ],
  [
    "src/connection.js~connection#getvoteaccounts",
    "class/src/connection.js~Connection.html#instance-method-getVoteAccounts",
    "src/connection.js~Connection#getVoteAccounts",
    "method"
  ],
  [
    "src/connection.js~connection#onaccountchange",
    "class/src/connection.js~Connection.html#instance-method-onAccountChange",
    "src/connection.js~Connection#onAccountChange",
    "method"
  ],
  [
    "src/connection.js~connection#onprogramaccountchange",
    "class/src/connection.js~Connection.html#instance-method-onProgramAccountChange",
    "src/connection.js~Connection#onProgramAccountChange",
    "method"
  ],
  [
    "src/connection.js~connection#onslotchange",
    "class/src/connection.js~Connection.html#instance-method-onSlotChange",
    "src/connection.js~Connection#onSlotChange",
    "method"
  ],
  [
    "src/connection.js~connection#removeaccountchangelistener",
    "class/src/connection.js~Connection.html#instance-method-removeAccountChangeListener",
    "src/connection.js~Connection#removeAccountChangeListener",
    "method"
  ],
  [
    "src/connection.js~connection#removeprogramaccountchangelistener",
    "class/src/connection.js~Connection.html#instance-method-removeProgramAccountChangeListener",
    "src/connection.js~Connection#removeProgramAccountChangeListener",
    "method"
  ],
  [
    "src/connection.js~connection#removeslotchangelistener",
    "class/src/connection.js~Connection.html#instance-method-removeSlotChangeListener",
    "src/connection.js~Connection#removeSlotChangeListener",
    "method"
  ],
  [
    "src/connection.js~connection#requestairdrop",
    "class/src/connection.js~Connection.html#instance-method-requestAirdrop",
    "src/connection.js~Connection#requestAirdrop",
    "method"
  ],
  [
    "src/connection.js~connection#sendrawtransaction",
    "class/src/connection.js~Connection.html#instance-method-sendRawTransaction",
    "src/connection.js~Connection#sendRawTransaction",
    "method"
  ],
  [
    "src/connection.js~connection#sendtransaction",
    "class/src/connection.js~Connection.html#instance-method-sendTransaction",
    "src/connection.js~Connection#sendTransaction",
    "method"
  ],
  [
    "src/connection.js~contactinfo",
    "typedef/index.html#static-typedef-ContactInfo",
    "src/connection.js~ContactInfo",
    "typedef"
  ],
  [
    "src/connection.js~epochinfo",
    "typedef/index.html#static-typedef-EpochInfo",
    "src/connection.js~EpochInfo",
    "typedef"
  ],
  [
    "src/connection.js~epochschedule",
    "typedef/index.html#static-typedef-EpochSchedule",
    "src/connection.js~EpochSchedule",
    "typedef"
  ],
  [
    "src/connection.js~inflation",
    "typedef/index.html#static-typedef-Inflation",
    "src/connection.js~Inflation",
    "typedef"
  ],
  [
    "src/connection.js~keyedaccountinfo",
    "typedef/index.html#static-typedef-KeyedAccountInfo",
    "src/connection.js~KeyedAccountInfo",
    "typedef"
  ],
  [
    "src/connection.js~signaturesuccess",
    "typedef/index.html#static-typedef-SignatureSuccess",
    "src/connection.js~SignatureSuccess",
    "typedef"
  ],
  [
    "src/connection.js~transactionerror",
    "typedef/index.html#static-typedef-TransactionError",
    "src/connection.js~TransactionError",
    "typedef"
  ],
  [
    "src/connection.js~version",
    "typedef/index.html#static-typedef-Version",
    "src/connection.js~Version",
    "typedef"
  ],
  [
    "src/connection.js~voteaccountinfo",
    "typedef/index.html#static-typedef-VoteAccountInfo",
    "src/connection.js~VoteAccountInfo",
    "typedef"
  ],
  [
    "src/connection.js~voteaccountstatus",
    "typedef/index.html#static-typedef-VoteAccountStatus",
    "src/connection.js~VoteAccountStatus",
    "typedef"
  ],
  [
    "src/fee-calculator.js",
    "file/src/fee-calculator.js.html",
    "src/fee-calculator.js",
    "file"
  ],
  [
    "src/fee-calculator.js~feecalculator",
    "typedef/index.html#static-typedef-FeeCalculator",
    "src/fee-calculator.js~FeeCalculator",
    "typedef"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/layout.js",
    "file/src/layout.js.html",
    "src/layout.js",
    "file"
  ],
  [
    "src/loader.js",
    "file/src/loader.js.html",
    "src/loader.js",
    "file"
  ],
  [
    "src/loader.js~loader.chunksize",
    "class/src/loader.js~Loader.html#static-get-chunkSize",
    "src/loader.js~Loader.chunkSize",
    "member"
  ],
  [
    "src/loader.js~loader.getminnumsignatures",
    "class/src/loader.js~Loader.html#static-method-getMinNumSignatures",
    "src/loader.js~Loader.getMinNumSignatures",
    "method"
  ],
  [
    "src/loader.js~loader.load",
    "class/src/loader.js~Loader.html#static-method-load",
    "src/loader.js~Loader.load",
    "method"
  ],
  [
    "src/publickey.js",
    "file/src/publickey.js.html",
    "src/publickey.js",
    "file"
  ],
  [
    "src/publickey.js~publickey#constructor",
    "class/src/publickey.js~PublicKey.html#instance-constructor-constructor",
    "src/publickey.js~PublicKey#constructor",
    "method"
  ],
  [
    "src/publickey.js~publickey#equals",
    "class/src/publickey.js~PublicKey.html#instance-method-equals",
    "src/publickey.js~PublicKey#equals",
    "method"
  ],
  [
    "src/publickey.js~publickey#tobase58",
    "class/src/publickey.js~PublicKey.html#instance-method-toBase58",
    "src/publickey.js~PublicKey#toBase58",
    "method"
  ],
  [
    "src/publickey.js~publickey#tobuffer",
    "class/src/publickey.js~PublicKey.html#instance-method-toBuffer",
    "src/publickey.js~PublicKey#toBuffer",
    "method"
  ],
  [
    "src/publickey.js~publickey#tostring",
    "class/src/publickey.js~PublicKey.html#instance-method-toString",
    "src/publickey.js~PublicKey#toString",
    "method"
  ],
  [
    "src/publickey.js~publickey.ispublickey",
    "class/src/publickey.js~PublicKey.html#static-method-isPublicKey",
    "src/publickey.js~PublicKey.isPublicKey",
    "method"
  ],
  [
    "src/system-program.js",
    "file/src/system-program.js.html",
    "src/system-program.js",
    "file"
  ],
  [
    "src/system-program.js~systeminstruction#amount",
    "class/src/system-program.js~SystemInstruction.html#instance-get-amount",
    "src/system-program.js~SystemInstruction#amount",
    "member"
  ],
  [
    "src/system-program.js~systeminstruction#constructor",
    "class/src/system-program.js~SystemInstruction.html#instance-constructor-constructor",
    "src/system-program.js~SystemInstruction#constructor",
    "method"
  ],
  [
    "src/system-program.js~systeminstruction#frompublickey",
    "class/src/system-program.js~SystemInstruction.html#instance-get-fromPublicKey",
    "src/system-program.js~SystemInstruction#fromPublicKey",
    "member"
  ],
  [
    "src/system-program.js~systeminstruction#topublickey",
    "class/src/system-program.js~SystemInstruction.html#instance-get-toPublicKey",
    "src/system-program.js~SystemInstruction#toPublicKey",
    "member"
  ],
  [
    "src/system-program.js~systeminstruction#type",
    "class/src/system-program.js~SystemInstruction.html#instance-member-type",
    "src/system-program.js~SystemInstruction#type",
    "member"
  ],
  [
    "src/system-program.js~systeminstruction.from",
    "class/src/system-program.js~SystemInstruction.html#static-method-from",
    "src/system-program.js~SystemInstruction.from",
    "method"
  ],
  [
    "src/system-program.js~systeminstructiontype",
    "typedef/index.html#static-typedef-SystemInstructionType",
    "src/system-program.js~SystemInstructionType",
    "typedef"
  ],
  [
    "src/system-program.js~systemprogram.assign",
    "class/src/system-program.js~SystemProgram.html#static-method-assign",
    "src/system-program.js~SystemProgram.assign",
    "method"
  ],
  [
    "src/system-program.js~systemprogram.createaccount",
    "class/src/system-program.js~SystemProgram.html#static-method-createAccount",
    "src/system-program.js~SystemProgram.createAccount",
    "method"
  ],
  [
    "src/system-program.js~systemprogram.createaccountwithseed",
    "class/src/system-program.js~SystemProgram.html#static-method-createAccountWithSeed",
    "src/system-program.js~SystemProgram.createAccountWithSeed",
    "method"
  ],
  [
    "src/system-program.js~systemprogram.programid",
    "class/src/system-program.js~SystemProgram.html#static-get-programId",
    "src/system-program.js~SystemProgram.programId",
    "member"
  ],
  [
    "src/system-program.js~systemprogram.transfer",
    "class/src/system-program.js~SystemProgram.html#static-method-transfer",
    "src/system-program.js~SystemProgram.transfer",
    "method"
  ],
  [
    "src/sysvar-rent.js",
    "file/src/sysvar-rent.js.html",
    "src/sysvar-rent.js",
    "file"
  ],
  [
    "src/timing.js",
    "file/src/timing.js.html",
    "src/timing.js",
    "file"
  ],
  [
    "src/transaction.js",
    "file/src/transaction.js.html",
    "src/transaction.js",
    "file"
  ],
  [
    "src/transaction.js~transaction#add",
    "class/src/transaction.js~Transaction.html#instance-method-add",
    "src/transaction.js~Transaction#add",
    "method"
  ],
  [
    "src/transaction.js~transaction#addsigner",
    "class/src/transaction.js~Transaction.html#instance-method-addSigner",
    "src/transaction.js~Transaction#addSigner",
    "method"
  ],
  [
    "src/transaction.js~transaction#constructor",
    "class/src/transaction.js~Transaction.html#instance-constructor-constructor",
    "src/transaction.js~Transaction#constructor",
    "method"
  ],
  [
    "src/transaction.js~transaction#instructions",
    "class/src/transaction.js~Transaction.html#instance-member-instructions",
    "src/transaction.js~Transaction#instructions",
    "member"
  ],
  [
    "src/transaction.js~transaction#recentblockhash",
    "class/src/transaction.js~Transaction.html#instance-member-recentBlockhash",
    "src/transaction.js~Transaction#recentBlockhash",
    "member"
  ],
  [
    "src/transaction.js~transaction#serialize",
    "class/src/transaction.js~Transaction.html#instance-method-serialize",
    "src/transaction.js~Transaction#serialize",
    "method"
  ],
  [
    "src/transaction.js~transaction#sign",
    "class/src/transaction.js~Transaction.html#instance-method-sign",
    "src/transaction.js~Transaction#sign",
    "method"
  ],
  [
    "src/transaction.js~transaction#signpartial",
    "class/src/transaction.js~Transaction.html#instance-method-signPartial",
    "src/transaction.js~Transaction#signPartial",
    "method"
  ],
  [
    "src/transaction.js~transaction#signature",
    "class/src/transaction.js~Transaction.html#instance-get-signature",
    "src/transaction.js~Transaction#signature",
    "member"
  ],
  [
    "src/transaction.js~transaction#signatures",
    "class/src/transaction.js~Transaction.html#instance-member-signatures",
    "src/transaction.js~Transaction#signatures",
    "member"
  ],
  [
    "src/transaction.js~transaction.from",
    "class/src/transaction.js~Transaction.html#static-method-from",
    "src/transaction.js~Transaction.from",
    "method"
  ],
  [
    "src/transaction.js~transaction.fromrpcresult",
    "class/src/transaction.js~Transaction.html#static-method-fromRpcResult",
    "src/transaction.js~Transaction.fromRpcResult",
    "method"
  ],
  [
    "src/transaction.js~transactionctorfields",
    "typedef/index.html#static-typedef-TransactionCtorFields",
    "src/transaction.js~TransactionCtorFields",
    "typedef"
  ],
  [
    "src/transaction.js~transactioninstruction#constructor",
    "class/src/transaction.js~TransactionInstruction.html#instance-constructor-constructor",
    "src/transaction.js~TransactionInstruction#constructor",
    "method"
  ],
  [
    "src/transaction.js~transactioninstruction#data",
    "class/src/transaction.js~TransactionInstruction.html#instance-member-data",
    "src/transaction.js~TransactionInstruction#data",
    "member"
  ],
  [
    "src/transaction.js~transactioninstruction#keys",
    "class/src/transaction.js~TransactionInstruction.html#instance-member-keys",
    "src/transaction.js~TransactionInstruction#keys",
    "member"
  ],
  [
    "src/transaction.js~transactioninstruction#programid",
    "class/src/transaction.js~TransactionInstruction.html#instance-member-programId",
    "src/transaction.js~TransactionInstruction#programId",
    "member"
  ],
  [
    "src/transaction.js~transactioninstructionctorfields",
    "typedef/index.html#static-typedef-TransactionInstructionCtorFields",
    "src/transaction.js~TransactionInstructionCtorFields",
    "typedef"
  ],
  [
    "src/transaction.js~transactionsignature",
    "typedef/index.html#static-typedef-TransactionSignature",
    "src/transaction.js~TransactionSignature",
    "typedef"
  ],
  [
    "src/util/send-and-confirm-raw-transaction.js",
    "file/src/util/send-and-confirm-raw-transaction.js.html",
    "src/util/send-and-confirm-raw-transaction.js",
    "file"
  ],
  [
    "src/util/send-and-confirm-transaction.js",
    "file/src/util/send-and-confirm-transaction.js.html",
    "src/util/send-and-confirm-transaction.js",
    "file"
  ],
  [
    "src/util/shortvec-encoding.js",
    "file/src/util/shortvec-encoding.js.html",
    "src/util/shortvec-encoding.js",
    "file"
  ],
  [
    "src/util/sleep.js",
    "file/src/util/sleep.js.html",
    "src/util/sleep.js",
    "file"
  ],
  [
    "src/util/testnet.js",
    "file/src/util/testnet.js.html",
    "src/util/testnet.js",
    "file"
  ],
  [
    "src/validator-info.js",
    "file/src/validator-info.js.html",
    "src/validator-info.js",
    "file"
  ],
  [
    "src/validator-info.js~info",
    "typedef/index.html#static-typedef-Info",
    "src/validator-info.js~Info",
    "typedef"
  ],
  [
    "src/validator-info.js~validatorinfo#constructor",
    "class/src/validator-info.js~ValidatorInfo.html#instance-constructor-constructor",
    "src/validator-info.js~ValidatorInfo#constructor",
    "method"
  ],
  [
    "src/validator-info.js~validatorinfo#info",
    "class/src/validator-info.js~ValidatorInfo.html#instance-member-info",
    "src/validator-info.js~ValidatorInfo#info",
    "member"
  ],
  [
    "src/validator-info.js~validatorinfo#key",
    "class/src/validator-info.js~ValidatorInfo.html#instance-member-key",
    "src/validator-info.js~ValidatorInfo#key",
    "member"
  ],
  [
    "src/validator-info.js~validatorinfo.fromconfigdata",
    "class/src/validator-info.js~ValidatorInfo.html#static-method-fromConfigData",
    "src/validator-info.js~ValidatorInfo.fromConfigData",
    "method"
  ],
  [
    "src/vote-account.js",
    "file/src/vote-account.js.html",
    "src/vote-account.js",
    "file"
  ],
  [
    "src/vote-account.js~voteaccount#authorizedvoterpubkey",
    "class/src/vote-account.js~VoteAccount.html#instance-member-authorizedVoterPubkey",
    "src/vote-account.js~VoteAccount#authorizedVoterPubkey",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#authorizedwithdrawerpubkey",
    "class/src/vote-account.js~VoteAccount.html#instance-member-authorizedWithdrawerPubkey",
    "src/vote-account.js~VoteAccount#authorizedWithdrawerPubkey",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#commission",
    "class/src/vote-account.js~VoteAccount.html#instance-member-commission",
    "src/vote-account.js~VoteAccount#commission",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#credits",
    "class/src/vote-account.js~VoteAccount.html#instance-member-credits",
    "src/vote-account.js~VoteAccount#credits",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#epoch",
    "class/src/vote-account.js~VoteAccount.html#instance-member-epoch",
    "src/vote-account.js~VoteAccount#epoch",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#epochcredits",
    "class/src/vote-account.js~VoteAccount.html#instance-member-epochCredits",
    "src/vote-account.js~VoteAccount#epochCredits",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#lastepochcredits",
    "class/src/vote-account.js~VoteAccount.html#instance-member-lastEpochCredits",
    "src/vote-account.js~VoteAccount#lastEpochCredits",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#nodepubkey",
    "class/src/vote-account.js~VoteAccount.html#instance-member-nodePubkey",
    "src/vote-account.js~VoteAccount#nodePubkey",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#rootslot",
    "class/src/vote-account.js~VoteAccount.html#instance-member-rootSlot",
    "src/vote-account.js~VoteAccount#rootSlot",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount#votes",
    "class/src/vote-account.js~VoteAccount.html#instance-member-votes",
    "src/vote-account.js~VoteAccount#votes",
    "member"
  ],
  [
    "src/vote-account.js~voteaccount.fromaccountdata",
    "class/src/vote-account.js~VoteAccount.html#static-method-fromAccountData",
    "src/vote-account.js~VoteAccount.fromAccountData",
    "method"
  ]
]